name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install deploya
        run: go install github.com/kushalsubedi/deploya@latest

      - name: Run deploya release
        run: deploya release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
